### ISSUE TITLE
Adding species layer to complex area brings in every occurrence record

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/spatial-hub#341] opened 2020-09-01 23:06 UTC
When adding a particularly complex area to SP, and then adding a species layer, instead of adding a single species to only the specified area as expected, it instead loads every occurrence record in every location (ignoring the species selection as well as the area). This affects uploaded shapefiles as well as areas already defined in spatial layers.

Issue raised in helpdesk ticket 91645, where a user is combining multiple areas from a layer and attempting to download records from the combined area (https://spatial.ala.org.au/?ss=1598923626401), and received records that fell outside of the defined areas as well. Also related to helpdesk ticket 82236, for which #308 was raised to fix.

As an easy example, this also affects the bushfire extents layer:

- Add the National Indicative Aggregated Fire Extent 2019-2020 area to SP via Gazetteer polygon option
- Add a single species (eg. Osphranter rufus) to SP, restricted to the fire extent areas
- Every occurrence record of every species is loaded, including outside the defined area.

![SP complex area all occurrence records](https://user-images.githubusercontent.com/57081387/91914363-36e2c880-ecfb-11ea-896e-d4c8d44c6cc0.png)

**Comment by Tasilee** [comment] 2020-09-02 00:28
Thanks @timhicks-ala. I'd hoped that this was fixed. There is a work-around: Use the defined area for Tools | Area report - interactive, and then download the relevant data - which could be filtered externally for the relevant species? This seems to work for the 37 combined DIWA areas.

**Comment by timhicks-ala** [comment] 2020-09-02 02:48
Looks like the area report isn't quite right either, it shows plenty of records outside of those areas: https://biocache.ala.org.au/occurrences/search?q=qid:1598923543842&fq=#tab_mapView

The original reporter seems okay to reduce the number of areas they're working with to work around the issue.

**Comment by timhicks-ala** [comment] 2020-09-11 03:20
Additionally raised in 92050

**Comment by timhicks-ala** [comment] 2020-09-14 23:12
A user has confirmed that while a particularly complex shape file can trigger this issue, reducing the overall size of the area does work around the issue (as they are able to work with multiple smaller areas), which suggests this issue is entirely based on the complexity of an uploaded area.

**Comment by nickdos** [comment] 2020-11-09 23:56
@adam-collins add commits.

**Comment by adam-collins** [comment] 2020-11-12 02:43
Partially resolved with https://github.com/AtlasOfLivingAustralia/spatial-hub/commit/267ceb21152999072564f87bcee691c8ee79e7b9

**Comment by adam-collins** [comment] 2020-11-12 08:39
related to #344

**Comment by qifeng-bai** [comment] 2021-03-28 22:07
@timhicks-ala  Would you please test again. I wonder if it has been fixed on test

**Comment by Tasilee** [comment] 2021-03-28 23:30
Not working as advertised on test. Mapping _Eucalyptus gunnii_ on area Tasmania (from ASGS States/Territories) maps all occurrence records everywhere. I gave up waiting for it to finish mapping.

**Comment by qifeng-bai** [comment] 2021-03-29 01:22
Reproduce this issue:
Add to map -> gazzetter area -> Tasmania from ASGS stats/territories 
Add species:  Eucalyptus gunnii 

Current implementation is to collect WKT from this layer and upload wkt to biocache. It would cause issue when WKT is too big.

Fix:  using layer, for example: cl1023 : Tasmania, instead of wkt

**Comment by qifeng-bai** [comment] 2021-03-29 05:33
Another issue is caused by two possible reasons:
1, oversized wkt
2, intersected polygons

Working case:
https://biocache.ala.org.au/ws/webportal/params/details/1616994553941

Find eucalyptus gunnii in two polygons

Broken case:
https://biocache.ala.org.au/ws/webportal/params/details/1616715731279
When we load complicated areas, query in BS lost species and wkt.
[aspis (1).zip](https://github.com/AtlasOfLivingAustralia/spatial-hub/files/6219496/aspis.1.zip)

**Comment by qifeng-bai** [comment] 2021-04-12 01:31
Depended on: https://github.com/AtlasOfLivingAustralia/biocache-service/issues/579

**Comment by qifeng-bai** [comment] 2021-07-14 23:44
Related to https://github.com/AtlasOfLivingAustralia/spatial-service/issues/120

**Comment by qifeng-bai** [comment] 2021-07-19 01:36
After updated Tomcat settings, I confirmed that  adding a species in a complicated area on Spatial-test and prod works now

**Closed** 2021-07-19 03:31 UTC
Labels: bug
